# Linux Pipeline for SoundBox

trigger:
- master
- azure-pipeline-cmake

pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
      cmake --version
      python3 --version
      mkdir build
      cd build
      cmake ../source
      cmake --build .
