# MacOS Pipeline for SoundBox

trigger:
- master
- develop/noise_1

pool:
  vmImage: 'macOS-latest'
steps:
- script: |
    cmake --version
    python3 --version
    c++ --version
    mkdir build
    cd build
    cmake ..
    cmake --build .
