# Windows build pipeline for SoundBox

trigger:
- master
- azure-pipeline-cmake

pool:
  vmImage: 'windows-latest'
steps:
- script: |
      echo hello from Windows
      systeminfo
      cd
      cmake --version
      python3 --version
      dir
      md build 2>&1
      cd build
      cd
      dir
      cmake ..\source
      cmake --build .
